### ISSUE TITLE
Connection refused when connecting from other IPs

### ISSUE THREAD

**Issue by jikelmon** [50ButtonsEach/fliclib-linux-hci#1]
Hey Guys,

first of all thank you for the new SDK!

Connecting the client running on localhost works like a charm!

But I have encountered a problem when trying to connect to your daemon from another device running on the local network. The connection gets refused.

Is it a security feature or am i doing something wrong?

**Comment by Emill** [comment]
Hi!

Nice you like the SDK.

When starting the daemon, add the --server-addr flag (-s for short) with the argument 0.0.0.0, that will bind the socket to all interfaces so you can access it from outside localhost.

`./flicd -f flic.db -s 0.0.0.0`

**Comment by jikelmon** [comment]
Thank you! This did the job! Debugging here we go! :)

Would it be possible to add all available parameters for your daemon in the readme?

**Comment by Emill** [comment]
Yes, good idea.
Otherwise just run flicd without parameters and you will see all available options.
