### ISSUE TITLE
Issue with different Linux version

### ISSUE THREAD

**Issue by kylinxun** [50ButtonsEach/fliclib-linux-hci#10]
Hi,

I had problem with running the server code.

Here is my Linux platform information:
Linux OpenWrt 3.10.14 #301 SMP Tue May 17 13:37:45 EDT 2016 mips GNU/Linux 

When I compile x86-64 version, I got Error Code:
./flicd: 1: ./flicd: Syntax error: word unexpected (expecting ")")

Is there anyway I can compile and run the server code?

Thank you.
Kyle

**Comment by Emill** [comment]
Hi.

It would be cool to run flic on a router!
It seems your processor has the MIPS architecture. The x86_64 binary only works for x86_64 CPUs.
I see your Linux kernel version seems to be 3.10. But version >= 3.13 is needed for flicd.

I'd like to ask some questions:
What router model do you have?
Has it support for Bluetooth? Has it support for Bluetooth Low Energy (introduced in Bluetooth 4.0)?
Does your system have libcurl installed?

**Comment by kylinxun** [comment]
Thank you for quick response.

I am interesting in a deeper conversion. Can you share your email?

Thank you.

**Comment by Emill** [comment]
It's emil@shortcutlabs.com
Den 17 maj 2016 22:09 skrev "kylinxun" <notifications@github.com>:

**Comment by yamiyang** [comment]
Hi, 

I have the same question.
my openwrt router kernel version:
"Linux OpenWrt 3.10.14 #2 SMP Mon Jul 18 15:20:34 CST 2016 mips GNU/Linux"
and I have 3 kernel patches:
Bluetooth: Introduce new HCI socket channel for user operation
Bluetooth: Introduce user channel flag for HCI devices
Bluetooth: Refactor raw socket filter into more readable code

is it possible run flicd on my openwrt router ?

**Comment by Emill** [comment]
I guess so. There are some more later commits in the Linux kernel regarding
hci channel user but I don't think they are necessary.
Den 20 jul 2016 04:26 skrev "yamiyang" <notifications@github.com>:

**Comment by Emill** [comment]
Or aha you're also running mips... There is no binary for mips yet. Do you
use uclibc or the newer musl?

I guess so. There are some more later commits in the Linux kernel regarding
hci channel user but I don't think they are necessary.
Den 20 jul 2016 04:26 skrev "yamiyang" <notifications@github.com>:

**Comment by yamiyang** [comment]
I use uclibc.
do you have plan for mips binary release?
