### ISSUE TITLE
Building for Mac Catalyst with Xcode 12

### ISSUE THREAD

**Issue by arlomedia** [50ButtonsEach/fliclib-linux-hci#100]
I'm using the fliclib framework in my iOS and Mac Catalyst project. I have the latest version of the framework (1.4.0), I have the project set to embed it only in iOS, and I have all the related code hidden from macOS with _#if !TARGET_OS_MACCATALYST_.

Before Xcode 12, the project would build for both platforms. With Xcode 12, the project will only build for iOS with the framework set to "Embed and Sign" and will only build for macOS with the framework set to "Embed Without Signing." I'm attaching the error that is shown if I try building with "Embed and Sign" as in previous Xcode versions. Two other third-party frameworks are fine.

Is this an issue with Xcode, or something that needs to be addressed in the framework?

![Screen Shot 2020-09-23 at 1 04 28 PM](https://user-images.githubusercontent.com/1878401/94064187-296eaa80-fd9e-11ea-9f49-707e2fbc51c6.png)

![Screen Shot 2020-09-23 at 1 09 37 PM](https://user-images.githubusercontent.com/1878401/94064201-2d9ac800-fd9e-11ea-9d7a-a34ef67bc24a.png)

**Comment by Emill** [comment]
Hi. Could you please post this in the correct repository instead?
