### ISSUE TITLE
simpleclient build fails on Raspberry Pi

### ISSUE THREAD

**Issue by Sivivatu** [50ButtonsEach/fliclib-linux-hci#108]
I'm trying to configure the SDK on an RPi 3 and when I try to run make on the simpleclient the make fails with a generic Error 1.

When executing make I do see numerous errors:
```
/usr/include/c++/10/new:135:42: error: expected initializer before ‘_GLIBCXX_USE_NOEXCEPT’
  135 | void operator delete(void*, std::size_t) _GLIBCXX_USE_NOEXCEPT
```
But I have no idea how I would diagnose these. 
Any assistance would be apprectiated

**Comment by Emill** [comment]
Please post the full output from the compilation.

**Comment by Sivivatu** [comment]
> Please post the full output from the compilation.

What would be the best way to do that? Pipe the result into a text file?

**Comment by Emill** [comment]
Copy-paste from the terminal window?

**Comment by Sivivatu** [comment]
The printout is rather long so have attached it as a txt

[log.txt](https://github.com/50ButtonsEach/fliclib-linux-hci/files/7654874/log.txt)

**Comment by Emill** [comment]
I wonder if something is messed up with your build system.

Can you compile a very simple c++ file containing only these lines with `g++ file.cpp -c`?

```c++
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <poll.h>
#include <stdint.h>
#include <assert.h>

#include <string>
```

**Comment by Sivivatu** [comment]
looks like the same error to me but I have no experience with c++

[test_log.txt](https://github.com/50ButtonsEach/fliclib-linux-hci/files/7655833/test_log.txt)

**Comment by Emill** [comment]
Closing for now since it seems to be an issue with your build setup. Feel free to reopen if necessary.
