### ISSUE TITLE
Any plans for Python2 support?

### ISSUE THREAD

**Issue by CheapB** [50ButtonsEach/fliclib-linux-hci#11]

**Comment by Emill** [comment]
I had hoped that python3 would work for most people.
Feel free to port the python3 version to python2 and submit a pull request ;)

**Comment by CheapB** [comment]
All my other stuff is 2.xx and I am using AdaFruit WebIDE which is not supporting P3, so while P3 should be the way to go it is not yet for me..

**Comment by dly9014** [comment]
+1 for python2 support. My project for flic integration is stopped cold as the rest of it and prereqs are all python2.7. I started looking in to possibly using https://pypi.python.org/pypi/3to2, but haven't had time to pursue.
