### ISSUE TITLE
Compatibility with RPI 4?

### ISSUE THREAD

**Issue by matteo-tonini** [50ButtonsEach/fliclib-linux-hci#113]
Hi, 
I have recently switched to RPI 4 and I have some problems with my Flic setup.
Everything has been running just fine on the RPI 3B I had before.

Before digging deeper in what the problem could be, 
is this package compatible with RPI4?

I don't see it mentioned anywhere.

Thanks!

**Comment by Emill** [comment]
Yes! Raspberry Pi 3 is just mentioned as an example. It generally works with any Linux system having a Bluetooth controller attached.

**Comment by matteo-tonini** [comment]
Thanks for your prompt answer!
