### ISSUE TITLE
Get it running on Raspbian bookworm lite

### ISSUE THREAD

**Issue by pfink** [50ButtonsEach/fliclib-linux-hci#115]
Just if someone else has the same issue:

Trying to run it on Raspbian Bookworm Lite gave the following error: `-bash: /opt/fliclib-linux-hci/bin/armv6l/flicd: cannot execute: required file not found`

I could fix it by running:

```
sudo dpkg --add-architecture armhf
sudo apt update
sudo apt install -y libc6:armhf libstdc++6:armhf
```

**Comment by deanylev** [comment]
You are an absolute saint  🙏
