### ISSUE TITLE
Optionnaly Disable Double Click when connecting to a button

### ISSUE THREAD

**Issue by Roaders** [50ButtonsEach/fliclib-linux-hci#18]
Hi

Loving this library now, got it connected to my Pi3 last night and all is good.

Could we add the option to disable double click when we connect to a button? The button in my living room does nothing when double clicked but there is still the delay when clicking as the system is waiting to see if there is another click. If we could optionally disable double click on a per-button basis this would make the click more responsive.

**Comment by Emill** [comment]
The way is to simply listen for button down instead
Den 8 jun 2016 10:07 skrev "Roaders" <notifications@github.com>:

**Comment by Roaders** [comment]
button down won't work if you don't want the click even to fire when holding.

I can implement all this stuff in node and ignore all but button up and button down from the daemon but the daemon seems like the best place to do it - all client libraries then benefit.

**Comment by Emill** [comment]
Do you want to listen only to click and hold? Then you should listen to the
click / hold event rather than the single click / double click / hold event
;)
Den 10 jun 2016 09:15 skrev "Roaders" <notifications@github.com>:

**Comment by Roaders** [comment]
On one of my buttons yes I only want to listen to click and hold - but there is a (slight) delay when clicking as the system waits to see if there is another click before deciding to send a single click or double click event.

**Comment by Roaders** [comment]
Hmmmmm.... OK I'll have a look at that.
I think I am listening to buttonSingleOrDoubleOrHold (or whatever the exact name is) everywhere so I'll try that instead.
Thanks

**Comment by Roaders** [comment]
yes, buttonClick is what I want, not buttonSingleClick. Many Thanks.
