### ISSUE TITLE
Node Red Node updated for flic button

### ISSUE THREAD

**Issue by Roaders** [50ButtonsEach/fliclib-linux-hci#22]
Hi

Not an issue really but I thought that people might find this useful.

I've finished my node-red nod for the new flic lib as it all seems to be working pretty well on my set up at home. I am hoping that the publisher of the original library will accept my pull request and publish on npm but you can always get hold of the code from my repo here:

https://github.com/Roaders/node-red-contrib-flic-buttons

I have node-red running on one Raspberry Pi which actually connects to 2 flic daemons and responds to clicks from flic buttons throughout the house. I needed 2 Pis as some of the buttons were out of range.

I hope that people find it useful.

**Comment by readeral** [comment]
Thanks for this. I was really disappointed when I read the original npm package wasn't built on the new flic library, so glad you've done a lot of hard work. I'll be getting a new Pi soon and my Flics arrive this week, and I'll give it a crack. Hopefully your pull request is accepted soon.

**Comment by Roaders** [comment]
No sign of the pull request being accepted which is disappointing... you
can get it straight from github of course though. If it's not accepted I'll
publish under a new name which would be a shame.

When the next version of node-red is released I'll release another version
of the node with easier configuration.

**Comment by readeral** [comment]
Looks like you've made some progress with hardillb, hope it'll be done soon! In the meantime I'm going to grab your code and try using it. At the moment, I have no idea how to actually install fliclib-linux-hci though... first hurdles first

**Comment by readeral** [comment]
Hey Roaders, I'm not sure there's a more appropriate place to ask this, as I can't log an issue on your forked repo. I've successfully got all the flicd stuff working (flicd server is running, I can run 'node example.js' and see my button clicks, opening node-red outputs 'Accepted new client' in the flicd console) and placing a flic node on my canvas, with localhost and 5551 as my parameters it says 'connected'. Everything _seems_ fine, and yet, connecting that node to a debug node I don't get any result. Any idea what might be going on?

**Comment by Roaders** [comment]
You definitely need to enter the address. It's the address that is printed when you connect to the button, also the address that is printed when you run the example client in the lib folder.

Ah yes, this is a bit of an issue that forgotten about... I'll need to fix this...
You will need to enter your connection info then deploy the node-red flow (this connects to the daemon) then edit the flic button config node again and you should see a drop down list of addresses - select the one you want.
You can't display the list until the client is connected. You can't connect until you deploy so it's a 2 step process...

As I said I'll have to do something about that...

**Comment by readeral** [comment]
Thanks for getting back to me on this. Unfortunately I just can't get it to work how you describe.
- Dragging a node onto the canvas
- Edit flic node
- Select the pencil next to 'add new Flic Button...'
- Putting in '127.0.0.1' and '5551' (I've confirmed these against other clients, I think they're correct), gave it a name, and Address is greyed out at this stage
- Click update
- Select an Event type (selecting 'Button Click')
- Pressing OK and then deploying.
- Re-editing flic node results in Screen Shot 1
- Clicking the little pencil results in Screen Shot 2
 
![screenshot1](https://cloud.githubusercontent.com/assets/15904136/16169578/41ce7360-3577-11e6-946c-10a89c0e0e8c.png)
![screenshot2](https://cloud.githubusercontent.com/assets/15904136/16169579/41d95640-3577-11e6-8048-c43936787bf7.png)

Any sort of fiddling can't result in the drop down you describe. Again, I can see the flic respond when I have both a fliclib websocket server open, and the nodejs server. Both register the clicks, and the flic doesn't light up red. but, of course as the node-red instance isn't able to specify the button, when I press my button as expected it lights up red saying it can't find the server.

It might be worth removing the flic node files and starting again? Might have a bug?
Is there any funny thing about being a local or global package that I should worry about? Of course I'm manually putting the node folder in place, so I might be doing something wrong there too...

**Comment by Roaders** [comment]
No, thanks for your patience! I wrote that last reply in bed without actually checking anything but now I realise what the problem is. I didn't tell you to check out the branch rather than master.

You should checkout from here:

`https://github.com/Roaders/node-red-contrib-flic-buttons/tree/pre_node-red_0.14.0`

or 

`git checkout pre_node-red_0.14.0`

The version that you are looking at uses 2 levels of configuration node that is not yet supported.

Sorry about that.

**Comment by readeral** [comment]
Ah yes, I did check out master, I've downloaded the linked one now -
however, this is named 0.14.0 and I'm running 0.13.x - will that be a
problem?

Brilliant! It works. I didn't have a drop-down, but I could manually type
in my address and that was fine.

Initially had tried to run node-red after changing to the newly downloaded
branch, but I had a boot loop problem. I'd forgotten to remove the old flic
nodes and it was conflicting! Got that sorted though.

Thanks so much - hopefully others can come across this in the meantime
while waiting for the pull-request to come through.

On 18 June 2016 at 17:17, Roaders <notifications@github.com> wrote:

> No, thanks for your patience! I wrote that last reply in bed without
> actually checking anything but now I realise what the problem is. I didn't
> tell you to check out the branch rather than master.
>
> You should checkout from here:
>
>
> https://github.com/Roaders/node-red-contrib-flic-buttons/tree/pre_node-red_0.14.0
>
> or
>
> git checkout pre_node-red_0.14.0
>
> The version that you are looking at uses 2 levels of configuration node
> that is not yet supported.
>
> Sorry about that.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/50ButtonsEach/fliclib-linux-hci/issues/22#issuecomment-226926844>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APKtiF11p4YnlSghWx5261Yfq9WeBUtwks5qM5uSgaJpZM4Izjez>
> .
>



-- 

*Alan Reader| e. areader0@gmail.com <areader0@gmail.com> | m. 0400 215 751
| fb. - readeral <http://www.facebook.com/readeral> | i. -
instagram.com/readeral <http://instagram.com/readeral>*

**Comment by readeral** [comment]
If at some point you (or Hardillb I suppose) feel like putting 3 outputs on
the flic node, with the ability to map different click types to each, that
would be super great. For now it's relatively easy to make a subflow per
button.

On 18 June 2016 at 17:32, Al Reader <areader0@gmail.com> wrote:

> Ah yes, I did check out master, I've downloaded the linked one now -
> however, this is named 0.14.0 and I'm running 0.13.x - will that be a
> problem?
>
> Brilliant! It works. I didn't have a drop-down, but I could manually type
> in my address and that was fine.
>
> Initially had tried to run node-red after changing to the newly downloaded
> branch, but I had a boot loop problem. I'd forgotten to remove the old flic
> nodes and it was conflicting! Got that sorted though.
>
> Thanks so much - hopefully others can come across this in the meantime
> while waiting for the pull-request to come through.
>
> On 18 June 2016 at 17:17, Roaders <notifications@github.com> wrote:
>
>> No, thanks for your patience! I wrote that last reply in bed without
>> actually checking anything but now I realise what the problem is. I didn't
>> tell you to check out the branch rather than master.
>>
>> You should checkout from here:
>>
>>
>> https://github.com/Roaders/node-red-contrib-flic-buttons/tree/pre_node-red_0.14.0
>>
>> or
>>
>> git checkout pre_node-red_0.14.0
>>
>> The version that you are looking at uses 2 levels of configuration node
>> that is not yet supported.
>>
>> Sorry about that.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/50ButtonsEach/fliclib-linux-hci/issues/22#issuecomment-226926844>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/APKtiF11p4YnlSghWx5261Yfq9WeBUtwks5qM5uSgaJpZM4Izjez>
>> .
>>
>
>
>
> --
>
> *Alan Reader| e. areader0@gmail.com <areader0@gmail.com> | m. 0400 215 751
> <0400%20215%20751> | fb. - readeral <http://www.facebook.com/readeral> | i.
> - instagram.com/readeral <http://instagram.com/readeral>*
>



-- 

*Alan Reader| e. areader0@gmail.com <areader0@gmail.com> | m. 0400 215 751
| fb. - readeral <http://www.facebook.com/readeral> | i. -
instagram.com/readeral <http://instagram.com/readeral>*
