### ISSUE TITLE
Any chance to not take over the bluetooth controller?

### ISSUE THREAD

**Issue by yonilevy** [50ButtonsEach/fliclib-linux-hci#24]
The readme says:

> The downside however is that you will not be able to use that dedicated bluetooth controller for other bluetooth connections, such as streaming audio

I find this to be a big limitation of this implementation. Are there any plans to fix this / any workarounds to make the bluetooth controller available for other devices?

Thanks.

**Comment by readeral** [comment]
+1 - as much as I'm not currently using my RPi3 for anything else, it would be nice to be able to implement other bluetooth functions (like iBeacon) from my RPi without an additional dongle.

**Comment by Emill** [comment]
The Linux bluetooth stack BlueZ is not ready and mature yet to properly and
fully support Bluetooth low energy devices. If it was, we would be able to
fulfill your wishes.

If you still wish to try out a BlueZ implementation for Flic, check out the
fliclib-linux-dist repository, but it's not as stable as this project. Due
to instability and lack of important features in BlueZ, we created this
project.
Den 9 jul 2016 20:06 skrev "readeral" <notifications@github.com>:

**Comment by yonilevy** [comment]
Thanks for replying Emill, crazy that linux doesn't have a stable BLE stack :(

Are there any thoughts on open sourcing the Flic BT protocol, so other people can try and come up with implementations?

**Comment by Emill** [comment]
Not currently unfortunately. I don't get how that would help anyway since
most limitations are in the Bluetooth stacks themselves.
Den 10 jul 2016 14:16 skrev "Yoni Levy" <notifications@github.com>:

**Comment by yonilevy** [comment]
Maybe someone highly versed in BlueZ is also a flic fan and could help :)

**Comment by Emill** [comment]
Note that our Windows and Mac implementations of the same protocol does not take over the bluetooth controller, so if SDKs are available for those platforms for other Bluetooth stuff those operating systems can be used.
