### ISSUE TITLE
Issue with BCM20702-based dongle

### ISSUE THREAD

**Issue by etiago** [50ButtonsEach/fliclib-linux-hci#25]
Hi,

I have a dongle that's based on the BCM20702 chipset which, according to the README, should be supported. However, I'm getting really erratic behavior. The clicks don't register properly and I get the following messages sometimes:
```
104
client read failed: Connection reset by peer
A client was disconnected
A client was disconnected
A client was disconnected
A client was disconnected
A client was disconnected
A client was disconnected
Accepted new client
Warning: Non-standard-compliant or buggy bluetooth controller, sent 2 complete packets event, but there were only 1 outstanding for conhdl 64
Accepted new client
♥Received signal 2
A client was disconnected
A client was disconnected
```

This is running on a RPi (first edition) with the said dongle. If I run exactly the same thing on an RPi 3 with the built-in bluetooth, then I can get it to work.

Any ideas how can I make the dongle work? Have you heard of anything similar?

Thanks,
@etiago

**Comment by etiago** [comment]
Some more info... it seems this chipset is not as good as it would seem :( I found this: http://plugable.com/2014/06/23/plugable-usb-bluetooth-adapter-solving-hfphsp-profile-issues-on-linux although using that firmware didn't fix it for me.

**Comment by Emill** [comment]
Have you tried the same dongle on rpi3? (You will have to specify hci1)

Which dongle manufacturer do you have? Asus? Plugable?

Anyway those messages about outstanding packets have I also got with that
chip. But they are not that important. The new firmware has some fixes but
nothing really important for flic.

If clicks don't trigger immediately when you press your flic I think it is
due to a bad antenna inside the dongle. Rpi3 has much better antenna than
tiny budget dongles. Have you tried having the flic closer to the dongle?

torsdag 21 juli 2016 skrev Tiago Espinha <notifications@github.com>:

**Comment by etiago** [comment]
Hi @Emill ,

So weird! Just tried it on the RPi3, specified the hci1 (and I'm sure hci1 is the USB dongle, since I waited for the RPi to boot and *then* plugged it in) and it works! Perfectly fine, just like with the built-in bluetooth module.

Do you think this is caused by lack of processing power on the RPi1? I'm also going to try it on a RPi2 I have laying around... I was just trying to put this old RPi1 to good use since it's just been gathering dust and then I could reuse the RPi3 for other projects :smile: but I guess it's a no-go.

Thanks for your input!

**Comment by Emill** [comment]
Yes it could definitely be problems with the usb power, that's why I asked
you to test on rpi3 ;)

How powerful is your usb power supply? You can check this page
https://www.raspberrypi.org/help/faqs/#powerReqs for recommended numbers.

**Comment by etiago** [comment]
Hmm, I think it's not power issues... the power supply gives out 2A and I tested both the RPi1 and RPi3 exactly on the same power supply... I wouldn't be surprised though if the RPi1 just isn't able to output more than a set amount of current on the USB ports...

**Comment by etiago** [comment]
On a second look at that page you posted, indeed the RPi1 can only offer 500mA on the USB ports, which might not be enough to power the bluetooth dongle correctly... pity. But anyway, now we know. Thanks! :+1:

**Comment by etiago** [comment]
So... @Emill it turns out the problem has nothing to do with the current :fearful: it was actually my client's fault... it was throwing an Exception, which I consciously muffle during runtime, but was blinding me on the issue. Now it works fine on an RPi1 with an ORICO BTA-408.

**Comment by Emill** [comment]
Haha ok, no problems.
