### ISSUE TITLE
Logging to stdout

### ISSUE THREAD

**Issue by njh** [50ButtonsEach/fliclib-linux-hci#26]
Hello,

I am using daemontools as my process supervisor for flicd. It provides a mechanism to process the output of stdout and write it to disk (with timestamps, log rotation etc).

Passing ```-``` to the ```-l``` / ```--log-file``` argument of flicd causes it to write to a file called '-'. Please can you make it write to stdout instead, as is common behaviour?

I would submit a Pull Request, but....

Thanks,

nick.

**Comment by Emill** [comment]
Can't you just use /dev/stdout as `--log-file`? Or do you want `-`? :)

**Comment by njh** [comment]
Ah, yes. /dev/stdout works.

But I would expect most people would think ```-``` should work.
