### ISSUE TITLE
Websocket client

### ISSUE THREAD

**Issue by mikeboehm** [50ButtonsEach/fliclib-linux-hci#3]
I'm having trouble using the websocket client on a Raspberry Pi 3.

In one terminal:
`sudo ./flicd -f flic.sqlite3`

In the other:
`./websocketproxy localhost 5551 0.0.0.0 5553`
Which outputs
```
1 0.0.0.0 5553
waiting for client
```

I connect to the Pi in my browser, which returns a 404 with the text `Not Found`

Meanwhile, the websocket server has output the following
```
accept done
started thread
waiting for client
client_function
read request
client_function stopped
```

What am I missing?

**Comment by Emill** [comment]
Hi. The websocketproxy does not serve any html page.
Simply open up the index.html page in the client directory. Make sure the IP address in the html file is correct. Currently it's set to localhost.

**Comment by mikeboehm** [comment]
Ah! That would explain a lot.

Many thanks

**Comment by Emill** [comment]
Actually, I first thought about having the websocketproxy serve the html page as default, but found out that simply opening the html file locally would work as well.
