### ISSUE TITLE
Flic working on C.H.I.P

### ISSUE THREAD

**Issue by CheapB** [50ButtonsEach/fliclib-linux-hci#33]
One of the challenges with the setup is you need a computer pretty close to all your buttons, so the price of each computer becomes important if you want to deploy a lot of buttons. Because of this I tested out the $9 computer https://www.getchip.com/pages/chip and it seems to be working well with Flic.

When comparing with RPI and other platforms it becomes even more compelling. the Chip includes wifi and bluetooth and does nto need a SD card, where as those items are all extra on RPI. 

I am not associated with C.H.I.P - jut a happy customer :-)

**Comment by Emill** [comment]
Cool!
Definitely something to try out. Would you mind tell the specs of the BLE, i.e. number of maximum pending  connections + maximum concurrent connections (you need that many Flics to detect max concurrent)? That is reported by the "get info" command in the flicd protocol.

**Comment by CheapB** [comment]
The setup currently only running a single Flic as my "production" setup still runs RPI. This is what I am getting from Get_info: 

OrderedDict([('bluetooth_controller_state', <BluetoothControllerState.Attached: 2>), 
('my_bd_addr', 'cc:79:df:22:76:b4'), 
('my_bd_addr_type', <BdAddrType.PublicBdAddrType: 0>), 
('max_pending_connections', 32), 
('max_concurrently_connected_buttons', -1), 
('current_pending_connections', 0), 
('currently_no_space_for_new_connection', 0), 
('nb_verified_buttons', 1), 
('bd_addr_of_verified_buttons', ['80:e4:da:71:86:03'])])

**Comment by CheapB** [comment]
getting more and more excited about this setup. the range of bluetooth is MUCH better. I have just replaced 2 RPIs with a single CHIP. $9 for the CHIP + $3 for the power supply vs  2 x $35 for RPIs, 2 X $8 for SD cards and 2 x $4 for BT dongles and 1 x $8 for a wifi dongle (the other was wired) + 2 x $3 for power. $12 vs $108..  :-)  Only annoying thing is my favorite IDE from Adafruit is not supported on CHIP, so I will likely develop on RPI and then deploy to CHIP

**Comment by BandonRandon** [comment]
Thanks for your post @CheapB  I'm about to Flash my C.H.I.P. and give this a go :)
