### ISSUE TITLE
WizardInternetBackendError or InternetBackendError

### ISSUE THREAD

**Issue by eaandersen** [50ButtonsEach/fliclib-linux-hci#38]
I've attempted to pair/register more than one client to the same bluetooth controller and always receive the "InternetBackendError" error message. Can you please explain the error code?

**Comment by Emill** [comment]
Yes. It means our server couldn't be reached. Do you have Internet
connection?

Could you possibly send me a Wireshark capture of the network traffic?

Den 19 okt. 2016 6:43 em skrev "eaandersen" <notifications@github.com>:

**Comment by eaandersen** [comment]
Thank you for the reply. I have an internet connection on the device. I connect to the RPi remotely without issue and there's no issues connecting to external repositories (i.e. node, python). 

The device is connected to a corporate network and it is possible that traffic is blocked by a firewall. Is there a mechanism to add a client without connecting to the Flic server?

**Comment by Emill** [comment]
Do you know if dns requests are blocked on your network? Such are made to a
bunch of public dns servers in the Flic executable.

Anyway, could you try an earlier release? There the requests are made a bit
different.

Den 19 okt. 2016 7:38 em skrev "eaandersen" <notifications@github.com>:

**Comment by eaandersen** [comment]
Can you please specify the name(s) of the public DNS servers and the flic server name? I will test it out using host or dig from the terminal 

As for the earlier release, which one do you recommend? beta v0.1?

**Comment by Emill** [comment]
The used servers are 208.67.222.222, 8.8.8.8 and 209.244.0.3. The host "api.flic.io" is the one to be resolved.

You can test beta v0.1. It doesn't have the scan wizard so you have to simply start scan manually and then connect manually when you see it advertises in public mode.

**Comment by pfink** [comment]
I have exactly the same problem. First button was verified, but I'm not able to verify more buttons, always getting WizardInternetBackendError. I captured the traffic using Wireshark and two bridged network interfaces on my Windows PC (one interface connected to my RPI, the other one to my router). Just sent it to flic@shortcutlabs.com

Pinging  api.flic.io from my RPI:

```
ping api.flic.io
PING awseb-e-m-awsebloa-11wojfo0di1sp-1758411329.us-east-1.elb.amazonaws.com (54.209.22.83) 56(84) bytes of data.
^C
--- awseb-e-m-awsebloa-11wojfo0di1sp-1758411329.us-east-1.elb.amazonaws.com ping statistics ---
161 packets transmitted, 0 received, 100% packet loss, time 160010ms
```

**Comment by pfink** [comment]
Remark: I'm not connected to a corporate network or stuff like that, just using a normal router from my ISP. No firewalll for outgoing traffic configured.

**Comment by pfink** [comment]
Remark 2: Unlikely that 2 people experiencing this issue at exactly the same time even if there was time since July, isn't it? Maybe something is wrong with the server?

**Comment by Emill** [comment]
I checked your wireshark capture and everything looked fine there...
I'll look more into the issue tomorrow.
Could you just tell me, when you try to do the pairing, is the internet error coming out directly or after like 10 seconds? Also, does the flicd program print anything to its console log?

**Comment by pfink** [comment]
Thank you!

Log from simpleclient:

```
startScanWizard
Please click your Flic button!
Found private button. Please hold down it for 7 seconds to make it public.

<now I'm holding the button for 7 seconds, after that the following messages directly appear>

Found public button 80:e4:da:70:c9:4b F016cMlL, connecting...
Connected, now pairing and verifying...

<very short delay here, maybe 500ms or less>

Scan wizard done with status WizardInternetBackendError
```

Output of flicd:
```
Accepted new client
server error 0              //appears at the exact same time as WizardInternetBackendError
```

**Comment by Emill** [comment]
Could you try this: https://drive.google.com/open?id=0B-kW5rSvtUYnb29hNkpUT0xEaGs on your Raspberry Pi?
It adds some logging in the flicd output from the web request.

**Comment by pfink** [comment]
Hi,
I just tried with your patched version, but behaviour is exactly like before, no additional log messages.

**Comment by Emill** [comment]
Right.. try this one :)
I added even more logging
https://drive.google.com/open?id=0B-kW5rSvtUYnQWJldTBLN1pQOEk

**Comment by pfink** [comment]
I don't know why, but with this version it works fine! After I successfully added a second button, I switched back to the original flicd version to be sure and tried to connect a third button -> error message appears. Switching back to your patched version and trying to connect the third button again -> works fine.

I always used the same sqlite db for everything.

Log of a verify process on the patched version which worked fine:

```
Accepted new client
Connected
Wrote 98
Got 1024 bytes
Got 1024 bytes
Got 848 bytes
Got 1024 bytes
Got 1024 bytes
Got 897 bytes
Wrote 635
Got 91 bytes
Got 1024 bytes
incoming data 953 byes
Got 58 bytes
Incoming 1 0
got close
send close
Server response length: 953
First line: HTTP/1.1 200 OK
Wrote 69
Closing
```

**Comment by Emill** [comment]
That's strange... There is nothing different among them at all except the logging. Maybe you could try a few other times?

**Comment by pfink** [comment]
Ah, now I could reproduce the error with the version with logging (tried to connect again with a new db):

```
Accepted new client
Connected
Wrote 98
Got 1024 bytes
Got 1024 bytes
Got 848 bytes
Got 1024 bytes
Got 176 bytes
Got 1024 bytes
Got 721 bytes
Wrote 635
Got 91 bytes
Got 1024 bytes
incoming data 949 byes
Got 58 bytes
Incoming 1 0
got close
send close
Wrote 69
Closing
server error 0
```

**Comment by eaandersen** [comment]
Thank you for the update. Are you planning to push the changes to Github? Or do you prefer we use the file uploaded to Google Drive?

**Comment by Emill** [comment]
Yes I'll update the github repo as soon I get time.

Den 24 okt. 2016 8:15 em skrev "eaandersen" <notifications@github.com>:

**Comment by idserda** [comment]
I'm having this same issue, but then on a regular Ubuntu system. When will a binary for this be available?

**Comment by Emill** [comment]
@idserda I just created a new release. Could you try that one?

**Comment by Korydween** [comment]
@Emill  just for the feedback, I'm currently working with the new release and it works perfectly! Thanks.

**Comment by Christiandk1986** [comment]
I am having this issue also from the newest github verison. How do I resolve?

**Comment by Emill** [comment]
This is an already fixed issue. Exactly what issues do you have?

**Comment by Christiandk1986** [comment]
When I try to connect I get the following error (RPI 4, running 32bit Raspbian):

startScanWizard
Please click and hold down your Flic button!
Found private button. Please hold down it for 7 seconds to make it public.
Found public button 80:e4:da:74:XXXX F023dCiI, connecting...
Connected, now pairing and verifying...
Scan wizard done with status WizardInternetBackendError

**Comment by Emill** [comment]
Have you managed to connect the button to an Android or iOS device successfully?
If you have and fliclib-linux-hci doesn't work, please capture the network traffic using Wireshark, as well as run "sudo btmon" in a separate terminal to log the bluetooth packets, and post the results after a failed attempt.

**Comment by Christiandk1986** [comment]
I have paired the buttons many times before - always with ease. I do also have all the button adresses written down - am I able to use those to connect without the ScanWizcard?

**Comment by Emill** [comment]
Yes, but that won't make any difference. ScanWizard is simply a utility that performs scan and then connects.

**Comment by Christiandk1986** [comment]
Bluetooth monitor ver 5.50
= Note: Linux version 4.19.118-v7l+ (armv7l)                                                                   0.153041
= Note: Bluetooth subsystem version 2.22                                                                       0.153046
= New Index: DC:A6:32:B1:XX:XX (Primary,UART,hci0)                                                      [hci0] 0.153049
= Open Index: DC:A6:32:B1:XX:XX                                                                         [hci0] 0.153051
= Index Info: DC:A6:32:B1:XX:XX (Cypress Semiconductor Corporation)                                     [hci0] 0.153052
@ USER Open: flicd (privileged) version 2.22                                                   {0x0002} [hci0] 0.153056
@ MGMT Open: bluetoothd (privileged) version 1.14                                                     {0x0001} 0.153059
@ MGMT Open: btmon (privileged) version 1.14                                                          {0x0003} 0.153114

**Comment by Christiandk1986** [comment]
What am I looking for in Wireshark (rather than posting the entire log, which is huge)

**Comment by Christiandk1986** [comment]
Update: I have just tried installing a fresh Rasbian on a Pi Zero W and I keep getting the same error.

**Comment by Cyriuz** [comment]
I have the same issue I think on a RPI 4 with hassio; the flicd output is:
`TLS alert error: 46
server error 0`

I can't seem to ping api.flic.io either but it answers on http

**Comment by Emill** [comment]
@Cyriuz Do you use the latest published flicd here?

**Comment by davidjabon** [comment]
I also consistently keep getting the WizardInternetBackendError when attempting to connect the button to RaspberryPi Zero.  The button connects fine to a phone. I made sure to remove it from the phone before attempting to connect it to the RaspberryPi.

**Comment by davidjabon** [comment]
ping api.flic.io  doesn't work, perhaps by design.

wget https://api.flic.io/ping returns

--2020-05-31 15:45:26--  https://api.flic.io/ping
Resolving api.flic.io (api.flic.io)... 52.203.43.128
Connecting to api.flic.io (api.flic.io)|52.203.43.128|:443... connected.
ERROR: The certificate of ‘api.flic.io’ is not trusted.
ERROR: The certificate of ‘api.flic.io’ has expired.

curl https://api.flic.io/ping returns correctly: {"success":true}

**Comment by Cyriuz** [comment]
@Emill Using latest from here yes.

Both wget and curl work fine for me for api.flic.io, even inspecting the cert everything looks fine.

Can I somehow get more info from flicd which certificate it has a problem with?

**Comment by Emill** [comment]
For some reason the web server chose to send an expired intermediate certificate that affects some TLS clients. It should be fixed now so could you please try again?

**Comment by Christiandk1986** [comment]
Thx - It is working now!

**Comment by Cyriuz** [comment]
Yes, it works now, thank you!

**Comment by Emill** [comment]
Nice! and sorry for the inconvenience...

**Comment by davidjabon** [comment]
Thanks. It works now.
