### ISSUE TITLE
Error Timeout HCI after start of Daemon

### ISSUE THREAD

**Issue by pixelecho** [50ButtonsEach/fliclib-linux-hci#4]
I'm getting this error message after sarting the daemon. The error appears directly after starting with no client connected. Plattform ist RaspberryPi Model B running jessie and disabled bluez daemon.

Available HCI devices found:
hci0

Trying hci0
Successfully bound HCI socket
Flic server is now up and running!
Error: Timeout while initializing HCI, exiting. Try restart the program or replug your Bluetooth controller.
Exited

**Comment by Emill** [comment]
Hi. Can you attach the log from "sudo btmon"? First start btmon and then
the daemon.
Den 16 maj 2016 09:05 skrev "pixelecho" <notifications@github.com>:

**Comment by pixelecho** [comment]
Attached my btmon output

`
Bluetooth monitor ver 5.23
= New Index: 00:1F:CF:40:F7:29 (BR/EDR,USB,hci0)                                                                           [hci0] 0.218398
@ Index Removed
< HCI Command: Reset (0x03|0x0003) plen 0                                                                                 [hci0] 31.446552
> HCI Event: Command Complete (0x0e) plen 4                                                                               [hci0] 31.612121
      Reset (0x03|0x0003) ncmd 1
        Status: Success (0x00)
< HCI Command: Read Local Version Information (0x04|0x0001) plen 0                                                        [hci0] 31.613041
> HCI Event: Command Complete (0x0e) plen 12                                                                              [hci0] 31.622113
      Read Local Version Information (0x04|0x0001) ncmd 1
        Status: Success (0x00)
        HCI version: Bluetooth 2.0 (0x03) - Revision 3164 (0x0c5c)
        LMP version: Bluetooth 2.0 (0x03) - Subversion 3164 (0x0c5c)
        Manufacturer: Cambridge Silicon Radio (10)
< HCI Command: LE Read Supported States (0x08|0x001c) plen 0                                                              [hci0] 31.623185
> HCI Event: Command Status (0x0f) plen 4                                                                                 [hci0] 31.625095
      LE Read Supported States (0x08|0x001c) ncmd 1
        Status: Unknown HCI Command (0x01)
< HCI Command: Reset (0x03|0x0003) plen 0                                                                                 [hci0] 37.955759
> HCI Event: Command Complete (0x0e) plen 4                                                                               [hci0] 38.121825
      Reset (0x03|0x0003) ncmd 1
        Status: Success (0x00)
@ Index Added
@ New Settings: 0x0090
            bondable br/edr 
`

**Comment by Emill** [comment]
Oh. Your Bluetooth controller is too old (Bluetooth version 2.0). Bluetooth
low energy was introduced in Bluetooth 4.0.
Den 17 maj 2016 08:44 skrev "pixelecho" <notifications@github.com>:

**Comment by pixelecho** [comment]
Thanks problem solved with a new bluetooth dongle.
