### ISSUE TITLE
Emptying the stream of events

### ISSUE THREAD

**Issue by Korydween** [50ButtonsEach/fliclib-linux-hci#41]
Hi there !

First of all, thanks a lot for releasing this lib for linux. It is very useful and works very well. 
I have a simple question concerning a behavior a bit surprising. 

I modified the code from the examples to detect simple, double clicks and holds and  display "SimpleClick", "DoubleClick" or "Hold" on the corresponding event. It works very well, but the weird thing is when I click the button having neither the flicd nor the TestClient launched and the bluetooth off. When I launch both after having clicked a bit the button, the lines corresponding to the clicks I performed are displayed, as if the events were kept in memory by the button itself. 
I checked on my processes and I am pretty sure the flicd is not running when I click the button. 
Is this behavior normal?  If it is, is there a way to manually "empty" the stored events ? 

Thanks in advance for your answer.

**Comment by Emill** [comment]
Yes events are stored in RAM on the button itself if it is disconnected.
The events are delivered upon the next connection until it has received an acknowledgement that they have been arrived.

Simply use the two fields "was_queued" and "time_diff". See the documentation at https://github.com/50ButtonsEach/fliclib-linux-hci/blob/master/ProtocolDocumentation.md#evtbuttonevent.

**Comment by Korydween** [comment]
Thank you very much for the answer :) 
Next time I'll read the doc more carefully before asking a question :)
