### ISSUE TITLE
Really pleased so far

### ISSUE THREAD

**Issue by Roaders** [50ButtonsEach/fliclib-linux-hci#5]
Not really an issue but I don't think there's any other way of leaving feedback...

I had a play with this last night on Raspberry Pi 3 and got it up and running with the simple client.

How sure are we that this will carry on being supported (unlike the last library which I assume is being unsupported now).
I want to create a Node based client for it and don't want to put the work in if this library is not going to be maintained.

It's a shame that the server only talks in binary. It would be much easier (for me) to write a client if it was string based - or even just a REST api.

Thanks for the good work.

**Comment by Emill** [comment]
Hi.

Yes we intend to continue to support this SDK.
I just commited a Node.js client library that you could try out.

Regarding binary / text... The intention was that a binary protocol would be simpler, especially for C/C++. But I understand that it might be easier with text protocol for dynamic languages like python and js.

How would a REST api look like? Those are generally request - response apis but this one mainly focuses on events.

**Comment by Roaders** [comment]
Wow, thanks very much for the node library. Will doubtless save me some time. I'll try and have a play with it today sometime.

Yeah, I didn't really think the REST api through, ignore that!

**Comment by Roaders** [comment]
Ok, I tried the Node client and it all looks good and pretty easy to work with. I'm confident that I'll be able to create a node-red node for that fairly easily.
I am surprised at how quick it is. Using the flic mobile app it can be several seconds before clicking the button any anything happening if the phone or button have gone to sleep. With this it is pretty much instant even if it's been a long time since the last press.
it's nice to get all the events (up, down, click, double, hold) so that we have lots of flexibility - I can have a light come on just while I'm holding the button for example.

The click actions seems a bit slow - but that is of course because you're waiting for another click in case it's a double click. It is only a second or so and if that's a problem I can always just use up and down events.
