### ISSUE TITLE
flicd crashing repeatedly

### ISSUE THREAD

**Issue by hardillb** [50ButtonsEach/fliclib-linux-hci#54]
flicd won't run for more than about 30mins before it falls over with the following message:

```
$sudo ./flicd -f flic.sqlite3
Available HCI devices found:
hci0

Trying hci0
Successfully bound HCI socket
Flic server is now up and running!
Initialization of Bluetooth controller done!
Accepted new client
flicd: flicd.cpp:1614: void le_create_connection_handler(uint8_t): Assertion `!status || status == 0x09 || status == 0x07 || (!cant_scan_and_initiate && status == 0x0d)' failed.

```

I'm running on a raspberry pi with the an up to date jessie install. bluetoothd has been stopped.

I'm using a Cambridge Silicon Radio BLE dongle (CSR8510 A10)

**Comment by Emill** [comment]
Hi. Please run "sudo btmon" in a separate terminal, then start flicd. After crashing, post me the output from btmon.

**Comment by hardillb** [comment]
Took 2 hours this time to crash, but same error

[btmon.txt](https://github.com/50ButtonsEach/fliclib-linux-hci/files/922694/btmon.txt)

**Comment by Emill** [comment]
It seems you have some other process running that wants to enable advertising. I can see

```
< HCI Command: LE Set Advertise Enable (0x08|0x000a) plen 1
        Advertising: Enabled (0x01)
```

in the log. Try to find that process and exit it.

**Comment by hardillb** [comment]
Ahh, 

just remembered what else is running on that pi (https://github.com/hardillb/physical-web-lightswitch)

I'll move it to another pi
