### ISSUE TITLE
cannot run flicd: Unknown HCI command 

### ISSUE THREAD

**Issue by andreasloe** [50ButtonsEach/fliclib-linux-hci#56]
I cannot run flicd, btmon says
`@ USER Open: flicd (privileged) version 2.22          {0x0002} [hci0] 31.047166`
`< HCI Command: Reset (0x03|0x0003) plen 0                      [hci0] 31.047652`
`> HCI Event: Command Complete (0x0e) plen 4                    [hci0] 31.051109`
`      Reset (0x03|0x0003) ncmd 1`
`        Status: Success (0x00)`
`< HCI Command: Read Local Version Info.. (0x04|0x0001) plen 0  [hci0] 31.051520`
`> HCI Event: Command Complete (0x0e) plen 12                   [hci0] 31.053105`
`      Read Local Version Information (0x04|0x0001) ncmd 1`
`        Status: Success (0x00)`
`       HCI version: Bluetooth 2.1 (0x04) - Revision 0 (0x0000)`
`       LMP version: Bluetooth 2.1 (0x04) - Subversion 16899 (0x4203)`
`       Manufacturer: Broadcom Corporation (15)`
`         Firmware: 002.002.003`
`         Build: 0000`
`< HCI Command: LE Read Supported States (0x08|0x001c) plen 0   [hci0] 31.053420`
`> HCI Event: Command Complete (0x0e) plen 4                    [hci0] 31.055104`
`      LE Read Supported States (0x08|0x001c) ncmd 1`
`        Status: Unknown HCI Command (0x01)`
`@ USER Close: flicd                                   {0x0002} [hci0] 31.056478`
`= Close Index: 00:19:86:00:13:D5                               [hci0] 31.056661`
`@ MGMT Event: Index Added (0x0004) plen 0             {0x0001} [hci0] 31.056799`

**Comment by Emill** [comment]
Hi. Your Bluetooth controller has Bluetooth version 2.1. You need a controller with at least version 4.0.
