### ISSUE TITLE
How to stop the daemon?

### ISSUE THREAD

**Issue by DavidDeSloovere** [50ButtonsEach/fliclib-linux-hci#57]
Noob question, but couldn't figure it out on my own.
After running `./flicd -d -f flic.sqlite3` how can I stop the daemon so I can restart flicd without having to completely restart the raspberry pi?

Sidenote: I think the readme need some more information about getting fliclib downloaded/installed...

**Comment by Emill** [comment]
If you have a terminal window, you can press Ctrl+C.
I agree with you that we should have more documentation how to set up flicd as a background service on various Linux distributions...

**Comment by DavidDeSloovere** [comment]
thanks @Emill for the fast reply, but Ctrl+C only seems to work when flicd is starting in NON daemon mode. When started in daemon mode (with `-d` option) I get back to `$`.

**Comment by Emill** [comment]
Yes that's the whole point with a daemon :)
You need to kill the process if you start it as daemon through the Linux `kill` command.

**Comment by DavidDeSloovere** [comment]
`kill` is indeed what I was looking for.
After running `ps aux | grep flicd` I used the process id to run `kill 1181` et voila! Thanks.
