### ISSUE TITLE
hci0 is busy, shutting down and retrying...

### ISSUE THREAD

**Issue by kristoffernolgren** [50ButtonsEach/fliclib-linux-hci#60]
I'm running this on a rasberrypi, hasberry, (homeassistant)

I've been trying to shut of the bluetooth services, 

root       629  0.0  0.3   5008  3420 ?        Ss   15:51   0:00 /usr/lib/bluetooth/bluetoothd
pi         838  0.0  0.2   4276  1904 pts/0    S+   15:53   0:00 grep --color=auto bluetoothd

I can only shut down the root-one of them.

when I run
sudo ./flicd -f flic.sqlite3

I get this:
Available HCI devices found:
hci0

Trying hci0
hci0 is busy, shutting down and retrying...
Error bringing down hci: Device or resource busy
hci0 is busy, giving up

**Comment by Korydween** [comment]
Hi, 
I am having the same error message when I try to run it though it worked yesterday. did you solve your problem? I tried to restart the computer, restart the bluetooth, but still the same message.

**Comment by Emill** [comment]
Have you turned off bluetoothd?

**Comment by Korydween** [comment]
I deactivated bluetoothd by default since I am only using this computer for the buttons, but it seems it got reactivated somehow... Anyway, sorry for the bother and thank you for the very fast answer!
