### ISSUE TITLE
flicd does not work without internet connectivity

### ISSUE THREAD

**Issue by wschlich** [50ButtonsEach/fliclib-linux-hci#61]
flicd does not work without internet connectivity. this makes flic buttons useless in closed environments where there is no internet connectivity at all.

**Comment by Emill** [comment]
You can configure everything in an online environment and then take the db file to the computer without internet.
This will continue to be a Won'tfix.

**Comment by wschlich** [comment]
@Emill: I see. Thanks for pointing out a workaround, at least.
