### ISSUE TITLE
Can't pair - Home Assistant

### ISSUE THREAD

**Issue by schmidiij** [50ButtonsEach/fliclib-linux-hci#65]
Hello, 
i musst reset my raspi 3 and now, i can't pair the Flic Button with the new installed raspi.

What i did:
- a Factory reset (left the battary out for 10 sec and then back and hold the button for 15 sec

Then install the SDK
```
- service bluetooth stop
- git clone https://github.com/50ButtonsEach/fliclib-linux-hci.git
- cd fliclib-linux-hci/bin/armv6l
- sudo setcap cap_net_admin=ep ./flicd
- ./flicd -f flic.sqlite3
```

the service run but when a click the button for 7 sec, nothing happend.
What i do it wrong?

i use it for Home Assistant (www.home-assistant.io)

Thx for your help!

**Comment by mrwhale** [comment]
Looks like you need another step. You'll need to run a client, which connects to flicd, to actually do anything useful with your flics

` cd ~/fliclib-linux-hci/clientlib/nodejs`
` node newscanwizard.js`

From here you can attempt to pair a button

**Comment by schmidiij** [comment]
yes it's on the same Server (Raspi 3)

**Comment by devbobo** [comment]
@schmidiij did you set the `discovery` option to `true` ?
https://home-assistant.io/components/binary_sensor.flic/

**Comment by schmidiij** [comment]
yes.. but first musst the button paired with the Server - Flic Service? and this is the problem

**Comment by schmidiij** [comment]
.... i'm sorry. the Config-file wasn't without
```
binary_sensor:
  platform: flic
```

**Comment by schmidiij** [comment]
i write a tutorial for Home Assistant
[https://community.home-assistant.io/t/install-flic/16969/4?u=schmidij_ch](url)

i close this here
