### ISSUE TITLE
Disconnected BondingKeysMismatch

### ISSUE THREAD

**Issue by Roaders** [50ButtonsEach/fliclib-linux-hci#7]
I have the nodejs sample client up and running and got it connected to 2 buttons no problem. They both show button clicks and up and down events.

One of the buttons disconnected shortly after a button click with the message `Disconnected BondingKeysMismatch`.

Everything still works though and when I click the button again it re-connects no problem.

I didn't think that it was a problem until I noticed that the other button doesn't do it.

Should I be worried about this message?

Thanks

**Comment by Emill** [comment]
Hi.

This shouldn't happen. Did you get the `Disconnected BondingKeysMismatch` immediately after a connection had been established or when it had already been connected for a while?

Has this happened only once or does it happen frequently?

> I didn't think that it was a problem until I noticed that the other button doesn't do it.

What do you mean by *it*?

To help debugging, it would be nice if you had `sudo btmon` running in another terminal to get the logging.

**Comment by Roaders** [comment]
It happens pretty much every time I use the button - but not EVERY time. And as I said it's only this button, not the other button.
By it I mean the error message. I didn't think that it was a problem until I noticed that the other button wasn't giving that error.
It might be because I am testing the button without the back on - the back is still stuck to the place where I use the button but the button is on my desk. I think that I get the message when the battery pops out - maybe. not 100% sure.

node client output:

`pi@garagepi:~/git/fliclib-linux-hci/clientlib/nodejs $ node example.js
Connected to daemon!
80:e4:da:70:35:ec Connected
80:e4:da:70:35:ec Ready
80:e4:da:70:35:ec Disconnected BondingKeysMismatch
`

You can see that this time I didn't actually get the button click event (which is rare, most of the time I do)

btmon:

`Bluetooth monitor ver 5.23
= New Index: B8:27:EB:20:B8:68 (BR/EDR,UART,hci0)                                                                                               [hci0] 0.740233
> HCI Event: LE Meta Event (0x3e) plen 19                                                                                                       [hci0] 3.908495
      LE Connection Complete (0x01)
        Status: Success (0x00)
        Handle: 64
        Role: Master (0x00)
        Peer address type: Public (0x00)
        Peer address: 80:E4:DA:70:35:EC (OUI 80-E4-DA)
        Connection interval: 22.50 msec (0x0012)
        Connection latency: 0.00 msec (0x0000)
        Supervision timeout: 200 msec (0x0014)
        Master clock accuracy: 0x00
< ACL Data TX: Handle 64 flags 0x00 dlen 7                                                                                                      [hci0] 3.908659
      ATT: Read Request (0x0a) len 2
        Handle: 0x0012
< ACL Data TX: Handle 64 flags 0x00 dlen 9                                                                                                      [hci0] 3.908708
      ATT: Write Command (0x52) len 4
        Handle: 0x0013
          Data: 0100
< ACL Data TX: Handle 64 flags 0x00 dlen 9                                                                                                      [hci0] 3.908750
      ATT: Write Command (0x52) len 4
        Handle: 0x0016
          Data: 0100
< HCI Command: LE Remove Device From White List (0x08|0x0012) plen 7                                                                            [hci0] 3.908937
        Address type: Public (0x00)
        Address: 80:E4:DA:70:35:EC (OUI 80-E4-DA)
> HCI Event: Command Complete (0x0e) plen 4                                                                                                     [hci0] 3.912656
      LE Remove Device From White List (0x08|0x0012) ncmd 1
        Status: Success (0x00)
< HCI Command: LE Create Connection (0x08|0x000d) plen 25                                                                                       [hci0] 3.912759
        Scan interval: 60.000 msec (0x0060)
        Scan window: 30.000 msec (0x0030)
        Filter policy: White list is used (0x01)
        Peer address type: Public (0x00)
        Peer address: 00:00:00:00:00:00 (OUI 00-00-00)
        Own address type: Public (0x00)
        Min connection interval: 20.00 msec (0x0010)
        Max connection interval: 25.00 msec (0x0014)
        Connection latency: 0x0000
        Supervision timeout: 200 msec (0x0014)
        Min connection length: 0.000 msec (0x0000)
        Max connection length: 0.000 msec (0x0000)
> HCI Event: Command Status (0x0f) plen 4                                                                                                       [hci0] 3.913963
      LE Create Connection (0x08|0x000d) ncmd 1
        Status: Success (0x00)
> HCI Event: Number of Completed Packets (0x13) plen 5                                                                                          [hci0] 3.963992
        Num handles: 1
        Handle: 64
        Count: 2
> ACL Data RX: Handle 64 flags 0x02 dlen 25                                                                                                     [hci0] 4.008620
      ATT: Read Response (0x0b) len 20
        Value: 406f5f954e95bcfc87832934d674a41dd5027e97
< ACL Data TX: Handle 64 flags 0x00 dlen 27                                                                                                     [hci0] 4.008779
      ATT: Write Request (0x12) len 22
        Handle: 0x0012
          Data: 09b9135eb79159ad4beb8cd7a4b6a8006f400c49
< ACL Data TX: Handle 64 flags 0x00 dlen 21                                                                                                     [hci0] 4.008860
      ATT: Write Request (0x12) len 16
        Handle: 0x0012
          Data: 06000000000000ff0101b3ba340a
> ACL Data RX: Handle 64 flags 0x02 dlen 5                                                                                                      [hci0] 4.008987
      ATT: Write Response (0x13) len 0
> ACL Data RX: Handle 64 flags 0x02 dlen 5                                                                                                      [hci0] 4.009648
      ATT: Write Response (0x13) len 0
> HCI Event: Number of Completed Packets (0x13) plen 5                                                                                          [hci0] 4.031022
        Num handles: 1
        Handle: 64
        Count: 2
> ACL Data RX: Handle 64 flags 0x02 dlen 5                                                                                                      [hci0] 4.053206
      ATT: Write Response (0x13) len 0
> ACL Data RX: Handle 64 flags 0x02 dlen 5                                                                                                      [hci0] 4.053702
      ATT: Write Response (0x13) len 0
> ACL Data RX: Handle 64 flags 0x02 dlen 22                                                                                                     [hci0] 4.054531
      ATT: Handle Value Notification (0x1b) len 17
        Handle: 0x0015
          Data: 40bcca27f2c216790309e1b2c8e983
< HCI Command: LE Connection Update (0x08|0x0013) plen 14                                                                                       [hci0] 4.054714
        Handle: 64
        Min connection interval: 87.50 msec (0x0046)
        Max connection interval: 100.00 msec (0x0050)
        Connection latency: 0x0013
        Supervision timeout: 4010 msec (0x0191)
        Min connection length: 0.000 msec (0x0000)
        Max connection length: 0.000 msec (0x0000)
> ACL Data RX: Handle 64 flags 0x02 dlen 22                                                                                                     [hci0] 4.055942
      ATT: Handle Value Notification (0x1b) len 17
        Handle: 0x0015
          Data: 91010000110000000000006f5c1e05
> HCI Event: Command Status (0x0f) plen 4                                                                                                       [hci0] 4.057198
      LE Connection Update (0x08|0x0013) ncmd 1
        Status: Success (0x00)
> HCI Event: Number of Completed Packets (0x13) plen 5                                                                                          [hci0] 4.252741
        Num handles: 1
        Handle: 64
        Count: 1
> ACL Data RX: Handle 64 flags 0x02 dlen 22                                                                                                     [hci0] 4.271152
      ATT: Handle Value Notification (0x1b) len 17
        Handle: 0x0015
          Data: 60010000110000902644061e5fd36c
> ACL Data RX: Handle 64 flags 0x02 dlen 22                                                                                                     [hci0] 4.272566
      ATT: Handle Value Notification (0x1b) len 17
        Handle: 0x0015
          Data: 0802000011000000000000a0104467
> HCI Event: LE Meta Event (0x3e) plen 10                                                                                                       [hci0] 4.272774
      LE Connection Update Complete (0x03)
        Status: Success (0x00)
        Handle: 64
        Connection interval: 90.00 msec (0x0048)
        Connection latency: 23.75 msec (0x0013)
        Supervision timeout: 4010 msec (0x0191)
> HCI Event: Disconnect Complete (0x05) plen 4                                                                                                  [hci0] 8.321514
        Status: Success (0x00)
        Handle: 64
        Reason: Connection Timeout (0x08)
< HCI Command: LE Create Connection Cancel (0x08|0x000e) plen 0                                                                                 [hci0] 8.321752
> HCI Event: Command Complete (0x0e) plen 4                                                                                                     [hci0] 8.378438
      LE Create Connection Cancel (0x08|0x000e) ncmd 1
        Status: Success (0x00)
> HCI Event: LE Meta Event (0x3e) plen 19                                                                                                       [hci0] 8.378809
      LE Connection Complete (0x01)
        Status: Unknown Connection Identifier (0x02)
        Handle: 65
        Role: Master (0x00)
        Peer address type: Public (0x00)
        Peer address: 00:00:00:00:00:00 (OUI 00-00-00)
        Connection interval: 22.50 msec (0x0012)
        Connection latency: 0.00 msec (0x0000)
        Supervision timeout: 200 msec (0x0014)
        Master clock accuracy: 0x00
< HCI Command: LE Add Device To White List (0x08|0x0011) plen 7                                                                                 [hci0] 8.378897
        Address type: Public (0x00)
        Address: 80:E4:DA:70:35:EC (OUI 80-E4-DA)
> HCI Event: Command Complete (0x0e) plen 4                                                                                                     [hci0] 8.379499
      LE Add Device To White List (0x08|0x0011) ncmd 1
        Status: Success (0x00)
< HCI Command: LE Create Connection (0x08|0x000d) plen 25                                                                                       [hci0] 8.379576
        Scan interval: 60.000 msec (0x0060)
        Scan window: 30.000 msec (0x0030)
        Filter policy: White list is used (0x01)
        Peer address type: Public (0x00)
        Peer address: 00:00:00:00:00:00 (OUI 00-00-00)
        Own address type: Public (0x00)
        Min connection interval: 20.00 msec (0x0010)
        Max connection interval: 25.00 msec (0x0014)
        Connection latency: 0x0000
        Supervision timeout: 200 msec (0x0014)
        Min connection length: 0.000 msec (0x0000)
        Max connection length: 0.000 msec (0x0000)
> HCI Event: Command Status (0x0f) plen 4                                                                                                       [hci0] 8.380676
      LE Create Connection (0x08|0x000d) ncmd 1
        Status: Success (0x00)

`

**Comment by Emill** [comment]
Ah I see the mistake. Someone who can't count :)

		DisconnectReason: {
			Unspecified: 0,
			ConnectionEstablishmentFailed: 0,
			TimedOut: 1,
			BondingKeysMismatch: 2
		},

**Comment by Roaders** [comment]
So it's probably not a key mismatch error but something else...

**Comment by Emill** [comment]
So, just pushed a fix.

What happens is that the connection gets lost for some reason due to bad radio conditions.

**Comment by Roaders** [comment]
that's probably the battery then - as I said I don't have the twist back on the button so I think that the battery probably pops out.
As long as I know it's nothing to worry about!

Thanks
