### ISSUE TITLE
Is there support for PBF (Powered By Flic) buttons? - Error: WizardInternetBackendError

### ISSUE THREAD

**Issue by varhub** [50ButtonsEach/fliclib-linux-hci#70]
Hello,

I wonder to known if PBF buttons are supported and how to manage App Id & Secret.

I have not problems pairing flic buttons, connecting remote clients to observe flic clicks...
But with PBF buttons I got next error:
```
$ ./new_scan_wizard.py 
Welcome to Scan Wizard. Please press your Flic button.
Found a private button. Please hold it down for 7 seconds to make it public.
Found public button <mac> (<id>), now connecting...
The button was connected, now verifying...
Scan wizard completed with result ScanWizardResult.WizardInternetBackendError
```

**Comment by Emill** [comment]
No. Email us with your company name/app id and cpu architecture and we can build a custom version.

**Comment by Emill** [comment]
Sorry. Could you please resend the email? It seems it got lost in our support system...

**Comment by varhub** [comment]
Of course
