### ISSUE TITLE
EvtButtonEvent time_diff precision

### ISSUE THREAD

**Issue by skakri** [50ButtonsEach/fliclib-linux-hci#74]
It would be nice if `time_diff` could be fetched in ms not seconds.

**Comment by Emill** [comment]
Sure but it's not that easy due to that packets are queued and then sent over the BLE link with varying delay. Also milliseconds need a larger integer type which we don't have space for.

**Comment by Emill** [comment]
If you need low latency then use that option and stay connected. Time diff will only be nonzero if the event was queued up while the device was disconnected.

**Comment by skakri** [comment]
> If you need low latency then use that option and stay connected.

Does it affect the battery life severely?

**Comment by Emill** [comment]
If you have a stable connection, then no. If you have an unstable connection, then yes.
Is NormalLatency not good enough for you?

**Comment by skakri** [comment]
It's okay but not great as I need to calculate time compensation. For example – I wish to trigger action after 1500ms but I'll get a small drift on `was_queued` + `time_diff=0`. It's nothing critical but not perfect as well.
