### ISSUE TITLE
Does this support Flic Lights?

### ISSUE THREAD

**Issue by cooperaj** [50ButtonsEach/fliclib-linux-hci#77]
I'm looking at getting some of the lights version to work with my smart lighthing (Yeelight so not officially supported). Would this be able to act as a bridge with something like homeassistant or is the lights version locked down in that way?

**Comment by Emill** [comment]
You can use Flic Single in the Linux SDK just like any Flic.

**Comment by pfink** [comment]
@Emill: In #77 you gave the opposite answer that Flic Singles are not supported. Did that change?

**Comment by Emill** [comment]
Yes :)
