### ISSUE TITLE
How to Force disconnect via nodejs?

### ISSUE THREAD

**Issue by gizus** [50ButtonsEach/fliclib-linux-hci#79]
Hi there, 
I need to command 18 flic buttons with a raspberry (only 10 concurrent session).

Due to the fact that i DON'T need a high sensitivity or more than 10 concurrent actions, I could disconnect a button after a press event, so that it frees up a channel and next time will follow the "connected"-"ready" sequence.

Can't find the right syntax for doing that, I need some help, please.

**Comment by Emill** [comment]
If you set the auto disconnect time parameter to for example 10, the Flic will disconnect after 10 seconds of timeout.

**Comment by gizus** [comment]
Right, that was the other way, but I tried via simpleclient with no result (probably wrong syntax).
Would please state the right syntax for this command?
es. 
changeModeParameters 80:e4:da:73:6b:83 NormalLatency 2

**Comment by Emill** [comment]
That's correct but replace the full address with your connection id.

**Comment by Emill** [comment]
connect 80:e4:da:73:6b:83 0
    changeModeParameters 0 NormalLatency 2

**Comment by gizus** [comment]
ah ok button per button
What is the js equivalent? I could insert in the initial loop (taken form example.js)

client.once("ready", function() {
	var ora=new Date();
	console.log("Connesso a "+ora.getHours()+":"+ora.getMinutes()+":"+ora.getSeconds());
	client.getInfo(function(info) {
		info.bdAddrOfVerifiedButtons.forEach(function(bdAddr) {
			
                 // HERE //

			listenToButton(bdAddr);
		});
	});
});

**Comment by gizus** [comment]
Or, may I directly change it in the sqlite param file?

**Comment by Emill** [comment]
In the example, replace

    var cc = new FlicConnectionChannel(bdAddr);

with

    var cc = new FlicConnectionChannel(bdAddr, {autoDisconnectTime:2});

**Comment by gizus** [comment]
IT WORKS! 👍 
Thank you for you marvellous support!

**Comment by Emill** [comment]
No prob ;)
