### ISSUE TITLE
Flic on windows 10 fall creators update

### ISSUE THREAD

**Issue by aa4re** [50ButtonsEach/fliclib-linux-hci#80]
Flic on windows 10 fall creators update, please i need fix of the problem or source Code of flicSDK.exe to try to solve the problem, Thanks for the great work and time spent all these years

**Comment by aa4re** [comment]
I am disappointed with the lack of support for windows 10 Falls Creators. The Flic product has not helped me since I needed it to control an event from a distance in a measurement program made by c #. the FlukeConnect is connected by bluetooth BLE to the PC without problems or difficulties sending thousands of data, they work without the need even of SDK, and with your product you put so much difficulty just to send three data !!! do not even leave the operation offline or remove the dependence on your APP, I started a small project to make a small PCB with the new integrated Texas Instruments, I will keep the Flic buton to remove the plastic case and use it in something else ...

**Comment by fabianbergmark** [comment]
you haven't even included the error you experience. Please explain your problem in greater detail

**Comment by Emill** [comment]
Should be fixed in the latest FlicSDK for windows version.
