### ISSUE TITLE
le_set_scan_enable_handler Assertation '!status' failed

### ISSUE THREAD

**Issue by PeterEinberger** [50ButtonsEach/fliclib-linux-hci#9]
I'm trying to run the Server on a Raspberry Pi2 B and get:

Available HCI devices found:
hci0

Trying hci0
Successfully bound HCI socket
Flic server is now up and running!
Initialization of Bluetooth controller done!
flicd: flicd.cpp:1395: void le_set_scan_enable_handler(uint8_t): Assertion `!status' failed.

**Comment by Emill** [comment]
Hi. What is printed if you in parallel enable logging by executing `sudo btmon`?

**Comment by PeterEinberger** [comment]
Thx for the quick reply!

Bluetooth monitor ver 5.32
= New Index: 5C:F3:70:6D:8C:64 (BR/EDR,USB,hci0)                [hci0] 0.876072
@ Index Removed
< HCI Command: Reset (0x03|0x0003) plen 0                       [hci0] 2.921551
> HCI Event: Command Complete (0x0e) plen 4                     [hci0] 3.288246
      Reset (0x03|0x0003) ncmd 1
        Status: Success (0x00)
< HCI Command: Read Local Version Infor.. (0x04|0x0001) plen 0  [hci0] 3.288889
> HCI Event: Command Complete (0x0e) plen 12                    [hci0] 3.290211
      Read Local Version Information (0x04|0x0001) ncmd 1
        Status: Success (0x00)
        HCI version: Bluetooth 4.0 (0x06) - Revision 4096 (0x1000)
        LMP version: Bluetooth 4.0 (0x06) - Subversion 8718 (0x220e)
        Manufacturer: Broadcom Corporation (15)
          Firmware: 001.002.014 (BCM20702A1)
          Build: 0000
< HCI Command: LE Set Scan Enable (0x08|0x000c) plen 2          [hci0] 3.290661
        Scanning: Disabled (0x00)
        Filter duplicates: Enabled (0x01)
< HCI Command: LE Read Supported States (0x08|0x001c) plen 0    [hci0] 3.291064
> HCI Event: Command Complete (0x0e) plen 4                     [hci0] 3.292211
      LE Set Scan Enable (0x08|0x000c) ncmd 1
        Status: Command Disallowed (0x0c)
> HCI Event: Command Complete (0x0e) plen 12                    [hci0] 3.293233
      LE Read Supported States (0x08|0x001c) ncmd 1
        Status: Success (0x00)
        States: 0x000000001fffffff
          Non-connectable Advertising State
          Scannable Advertising State
          Connectable Advertising State
          High Duty Cycle Directed Advertising State
          Passive Scanning State
          Active Scanning State
          Initiating State
            and Connection State (Master Role)
          Connection State (Slave Role)
          Non-connectable Advertising State
            and Passive Scanning State
          Scannable Advertising State
            and Passive Scanning State
          Connectable Advertising State
            and Passive Scanning State
          High Duty Cycle Directed Advertising State
            and Passive Scanning State
          Non-connectable Advertising State
            and Active Scanning State
          Scannable Advertising State
            and Active Scanning State
          Connectable Advertising State
            and Active Scanning State
          High Duty Cycle Directed Advertising State
            and Active Scanning State
          Non-connectable Advertising State
            and Initiating State
          Scannable Advertising State
            and Initiating State
          Non-connectable Advertising State
            and Connection State (Master Role)
          Scannable Advertising State
            and Connection State (Master Role)
          Non-connectable Advertising State
            and Connection State (Slave Role)
          Scannable Advertising State
            and Connection State (Slave Role)
          Passive Scanning State
            and Initiating State
          Active Scanning State
            and Initiating State
          Passive Scanning State
            and Connection State (Master Role)
          Active Scanning State
            and Connection State (Master Role)
          Passive Scanning State
            and Connection State (Slave Role)
          Active Scanning State
            and Connection State (Slave Role)
          Initiating State
            and Connection State (Master Role)
            and Master Role & Master Role
@ Index Added

**Comment by Emill** [comment]
Hmm. The command

```
< HCI Command: LE Set Scan Enable (0x08|0x000c) plen 2          [hci0] 3.290661
        Scanning: Disabled (0x00)
        Filter duplicates: Enabled (0x01)
```
is not supposed to be sent by the flicd. I guess it is sent by someone else. But flicd should have exclusive access to the HCI.
Does this happen all the time? Have you tried to first turn off Bluez? (The bluetoothd program).
What operating system and version are you running? Linux version and distribution.

**Comment by PeterEinberger** [comment]
Yes, thank you. Bluetooth Service was stopped, but another project connected to the BT adapter.
It's a Debian wheezy 7.10 distribution.
After that worked, I got "server error 0" when connecting the flic. This was caused by a missing sqlite installation. Now everything works :)
