### ISSUE TITLE
Support Flic 2

### ISSUE THREAD

**Issue by joris-** [50ButtonsEach/fliclib-linux-hci#92]
Hi !

I try to make it work on my raspberry zero W with my news flic 2 but it doesn't works.

Is Flic version 2 supported by the SDK ?

Info : 
Flic 2 are detected with android App but not with mac osx app :/

Thanks for help

**Comment by Emill** [comment]
It will be updated before Christmas with Flic 2 support.

**Comment by ristomatti** [comment]
@joris- Check https://github.com/50ButtonsEach/fliclib-linux-hci/releases/tag/2.0.1

**Comment by joris-** [comment]
@ristomatti thanks, already tested yesterday ;)
